development:
  adapter: postgresql
  encoding: unicode
  database: spreecommercetest
  pool: 5
  password:
  port: 5432

test:
  adapter: postgresql
  encoding: unicode
  database: spreecommercedev
  pool: 5
  password:
  port: 5432

production:
  adapter: postgresql
  encoding: unicode
  database: spreecommercetest
  pool: 5
  password:
  port: 5432  
