development:
  adapter: postgresql
  encoding: unicode
  database: spreecommercetest
  pool: 5
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: spreecommercedev
  pool: 5
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: spreecommerceprod
  pool: 5
  password:  
